name: Build Flet APK

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Entra nella cartella Flet per installare i requisiti corretti
        cd Flet
        pip install flet flet-charts
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        cd ..

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.x'
        channel: 'stable'

    - name: Prepare Common Files for Flet
      run: |
        # Copia la cartella common dentro Flet così Flet può impacchettarla nell'APK
        cp -r common Flet/common

    - name: Build APK with Flet
      run: |
        cd Flet
        echo "y" | flet build apk
        cd ..
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: flet-release-apk
        path: Flet/build/apk/*.apk